version: '3.8'

networks:
  default:
    name: cinema-network
    external: true

services:
  recometl:
    container_name: recom-etl
    build:
      context: ..
      dockerfile: docker/dockerfiles/DockerfileRecomETL
    env_file: envs/etl.env
    external_links:
      - broker
      - redis
      - mongo

  recomapi:
    container_name: recom-api
    build:
      context: ..
      dockerfile: docker/dockerfiles/DockerfileRecomApi
    env_file: envs/api.env
    external_links:
      - mongo

  recomtrainer:
    container_name: recom-trainer
    build:
      context: ..
      dockerfile: docker/dockerfiles/DockerfileRecomModelTrainer
    env_file:
      - envs/recomtrainer.env
    volumes:
      - recommender:/models

  recomserver:
    container_name: recom-serving
    build:
      context: ..
      dockerfile: docker/dockerfiles/DockerfileRecomModelServer
    env_file:
      - envs/recomserver.env
    depends_on:
      - recomtrainer
    volumes:
      - recommender:/models:ro

volumes:
  recommender:
