# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommender.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11recommender.proto\x12\x11MoviesRecommender\"\x1f\n\x0bViewContext\x12\x10\n\x08movie_id\x18\x01 \x01(\t\"[\n\x19GetRecommendationsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12-\n\x05views\x18\x02 \x03(\x0b\x32\x1e.MoviesRecommender.ViewContext\" \n\x0cMovieContext\x12\x10\n\x08movie_id\x18\x01 \x01(\t\"M\n\x1aGetRecommendationsResponse\x12/\n\x06movies\x18\x01 \x03(\x0b\x32\x1f.MoviesRecommender.MovieContext2\x86\x01\n\x11MoviesRecommender\x12q\n\x12GetRecommendations\x12,.MoviesRecommender.GetRecommendationsRequest\x1a-.MoviesRecommender.GetRecommendationsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommender_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIEWCONTEXT._serialized_start=40
  _VIEWCONTEXT._serialized_end=71
  _GETRECOMMENDATIONSREQUEST._serialized_start=73
  _GETRECOMMENDATIONSREQUEST._serialized_end=164
  _MOVIECONTEXT._serialized_start=166
  _MOVIECONTEXT._serialized_end=198
  _GETRECOMMENDATIONSRESPONSE._serialized_start=200
  _GETRECOMMENDATIONSRESPONSE._serialized_end=277
  _MOVIESRECOMMENDER._serialized_start=280
  _MOVIESRECOMMENDER._serialized_end=414
# @@protoc_insertion_point(module_scope)
