from enum import Enum


class Genre(str, Enum):
    ACTION = "Action"
    ADVENTURE = "Adventure"
    FANTASY = "Fantasy"
    SCIFI = "Sci-Fi"
    DRAMA = "Drama"
    MUSIC = "Music"
    ROMANCE = "Romance"
    THRILLER = "Thriller"
    MYSTERY = "Mystery"
    COMEDY = "Comedy"
    ANIMATION = "Animation"
    FAMILY = "Family"
    BIOGRAPHY = "Biography"
    MUSICAL = "Musical"
    CRIME = "Crime"
    SHORT = "Short"
    WESTERN = "Western"
    DOCUMENTARY = "Documentary"
    HISTORY = "History"
    WAR = "War"
    GAMESHOW = "Game-Show"
    REALITYTV = "Reality-TV"
    HORROR = "Horror"
    SPORT = "Sport"
    TALKSHOW = "Talk-Show"
    NEWS = "News"
    CHILDRENS = "Children's"
    FILMNOIR = "Film-Noir"
